// 定义一个数组
let songs: string[] = ['告白气球', '洋葱', '吻别']

// 添加
// 1. 往开头新增 unshift(新增的值)  返回操作后的数组的长度
// songs.unshift('彩虹')
// console.log('返回数组长度', songs.unshift('七里香'))
// console.log('数组songs', songs)

// 2. 往结尾新增 push(新增的值)  返回操作后的数组的长度
// songs.push('光辉岁月', '海阔天空')
// console.log('数组', songs)

// 删除
// 1. 从开头删 shift
// console.log('返回删除的项', songs.shift())
// console.log('返回删除的项', songs.shift())
// console.log('数组', songs)

// 2. 从结尾删 pop
// songs.pop()
// songs.pop()
// songs.pop()
// console.log('数组', songs)

// 开头(S): unshift(开头增)  shift(开头删)
// 结尾(P): push(结尾增)  pop(结尾删)



@Entry
@Component
struct Index {
  build() {
    
  }
}