// 一元运算符(++  --)
// ++ 作用: 让变量,在原本基础之上加1
// let num: number = 10
// // num++ // 先赋值,后自增
// // ++num // 先自增,后赋值
// console.log('num', num)

// let num1: number = 10
// let res1: number = num1++
// console.log('res1', res1) // 10
// console.log('num1', num1) // 11
//
// let num2: number = 10
// let res2: number = ++num2
// console.log('res2', res2) // 11
// console.log('num2', num2) // 11
//
// let num2: number = 10
// let res2: number = --num2
// console.log('res2', res2) // 9
// console.log('num2', num2) // 9


@Entry
@Component
struct Index {
  build() {
    
  }
}