// 比较运算符 >  <   >=  <=   ==  !=
// let num1: number = 11
// let num2: number = 11
// console.log('判断结果', num1 > num2) // false
// console.log('判断结果', num1 < num2) // false
// console.log('判断结果', num1 >= num2) // true

// == != 判断是否相等(判断数字, 也会用来判断字符串)
// let num1: number = 200
// let num2: number = 201
// console.log('判断结果', num1 == num2)

// 判断密码是否正确
// let password: string = '123456'
// let password2: string = '123456'
// console.log('判断结果', password == password2)


@Entry
@Component
struct Index {
  build() {
    
  }
}